# Nombre de la aplicacion mostrado en los logs de arranque
spring.application.name=api-taller2

# Puerto en el que se publica la API REST (http://localhost:8080)
server.port=8080

# Devuelve el mensaje de las excepciones en las respuestas de error del servidor
server.error.include-message=always
